### ISSUE TITLE
哎 你们只负责写，小米账号和密码始终验证不过去

### ISSUE THREAD

**Issue by jjiikkkk** [Regularly-Archive/2023#1]
哎 验证不过去

**Comment by qinyuanpei** [comment]
理论上只需要填 .env 文件啊

**Comment by jjiikkkk** [comment]
我都没到那一步呢

**Comment by jjiikkkk** [comment]
我用了三个人github上的方法，基本上也是互相改造的，主要的问题都是小米账号过不去，而且有多个人也是过不去
从国外的云服务器换到了国内的云服务器，过不去
忙活了好几天了，线上的SSH，到本地的SSH，现在让我换linux for windows
都会出现micli的问题，都会出现path的问题，解决掉了，但是还是验证过去不，小米的账号都去小米手机里认证实名拍照和加了银行卡

**Comment by qinyuanpei** [comment]
这和服务器有什么关系呢？你首先导出 MI_User和 MI_Pass 两个变量，这个时候你就能到小爱同学的  DID，剩下都是基于 DID 来开展工作，我不明白你说的验证不过是什么意思，但理论上你能用这个账号登录米家，就可以拿到所有的设备信息，没有日志、没有截图，你不会觉得就靠三言两语别人就能帮你猜出原因吧

**Comment by jjiikkkk** [comment]
对啊 就是看不到DID啊，通不过服务器里的验证，除非拿着账号和密码 可以去其他地方找到DID 那就没问题

**Comment by qinyuanpei** [comment]
> 对啊 就是看不到DID啊，通不过服务器里的验证，除非拿着账号和密码 可以去其他地方找到DID 那就没问题

那试试 python-miio 这个库吧

**Comment by qinyuanpei** [comment]
请参考这个代码：https://github.com/Regularly-Archive/2023/blob/main/Jarvis/control/xiaomi.py

但我觉得它和 micli 的作用是一样的，我就是用这个方案控制小爱同学的啊，可谓是屡试不爽

**Comment by jjiikkkk** [comment]
我不太懂你写的，我试试看吧，ID和密码过不去是一大堆人的问题了，一大堆的人
最后得出的结论是，SSH全部不行，云服务器自身的控制台也不行，要WLS才可以

**Comment by qinyuanpei** [comment]
这个项目是基于 HTTP 协议的，我不知道你们到底在纠结什么，micli 本身不过是对 HTTP 协议的封装，可以实现米家设备的远程控制，仅此而已

**Comment by jjiikkkk** [comment]
我们要读取DID啊，都验证不过去 所以看不到DID
